### ISSUE TITLE
Cannot modify from command line a parameter introduced in a custom Profile

### ISSUE THREAD

**Issue by edobobo** [sunglasses-ai/classy#33]
**Describe the bug**
If you try to start a training modifying from the command line a parameter that has been introduced (i.e. was not in the default profile for the task you are doing) in a custom profile the process crashes.

**To Reproduce**
Create a custom model (CustomModel) with a custom parameter (custom_parameter). Then, create your own profile for the task (custom_profile). The model section of your profile will be something like this:

```yaml
model:
  _target_: my_project.my_models.CustomModel
  transformer_model: bert-base-cased
  custom_parameter: custom_value
```

Then run from the command line:
```bash
classy train my_task my_data -n my_model --profile custom_profile -c model.custom_parameter=new_value
```

**Expected behaviour**
The model should start with the model.custom_parameter set to the new value (new_value).

**Actual behaviour**
The training process crashes with the following hydra error:
```
Could not override 'model.custom_parameter'.
To append to your config use +model.custom_parameter=new_value
Key 'custom_parameter' is not in struct
    full_key: model.custom_parameter
    object_type=dict
```

**Desktop (please complete the following information):**
 - OS:  Ubuntu Server 20.04
 - PyTorch Version: 1.9.0
 - Classy Version: 0.1.0

**Comment by poccio** [comment]
#42 merged in develop, we can close the issue
