### ISSUE TITLE
How to fine-tune the existing model

### ISSUE THREAD

**Issue by yyq63728198** [sunglasses-ai/classy#79]
Hi,
I'm always frustrated when fine-tuning the checkpoint. There has no access to it, let alone continuing to train the SOTA model by a  different loss or use it as a submodule. 
I would be much grateful if you can provide this function.

**Comment by edobobo** [comment]
Hi, can you explain the problem more in detail and provide an example? (P.S. classy's version you are using would be appreciated too)

**Comment by yyq63728198** [comment]
Hi, I installed the `classy-core 0.2.1`

We can evaluate the the checkpoint model via `classy evaluate <model_path> <dataset> -pd extend`

For my research purpose, I wanted to train the trained model. So I tried `classy train <task> <dataset> -n <exp-name> <model_path>`, but it didn't work. 

So I'm puzzled how could I continue to train the trained model ?

**Comment by edobobo** [comment]
The easiest way is to extract the underlying transformer model and save it; then, you can use that transformer for another run.

This is the code to extract and store the underlying transformer model:
```python
pretrained_checkpoint = ESCModule.load_from_checkpoint("<ckpt-path>")
pretrained_checkpoint.longformer.save_pretrained("<transformer-path>")
```

Then you can continue to train the model with the following command:
```bash
classy train qa <folder> -n my-model-name --profile aida-longformer-large-gam -pd extend -c model.transformer_model="<transformer-path>"
```

**Comment by yyq63728198** [comment]
It works, Thanks a lot
