### ISSUE TITLE
Resume bug

### ISSUE THREAD

**Issue by andreim14** [sunglasses-ai/classy#83]
**Describe the bug**
The trainer parameters were not loaded correctly when the model was loaded from a checkpoint. E.g. val_check_interval was not set, so validation callbacks were not called rightly.

**To Reproduce**
Steps to reproduce the behaviour: 

1. Train a model for x steps
2. Stop the training
3. Restore the training from the checkpoint using _resume_from_ parameter

**Expected behaviour**
The trainer parameters should be preserved. E.g if val_check_interval is set, the validation callbacks should be called accordingly.

**Actual behaviour**
The validation callbacks are not called and val_check_interval is set to 0.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - PyTorch Version: 1.11

**Comment by poccio** [comment]
Issue has been resolved. Closing
