### ISSUE TITLE
Boundaries of adjacent entities

### ISSUE THREAD

**Issue by JuanFF** [sunglasses-ai/classy#85]
Hello,
Using the current token annotation format, I can't set the boundaries of the following entities (they all have the same label):

_name_ `personal_data`
_address_ `personal_data`
_id card number_ `personal_data`

...in the following example
_please tell me your **name** **address** and **identity card number**_

The resulting labeled sentence would be
`O O O O PERSONAL_DATA PERSONAL_DATA O PERSONAL_DATA PERSONAL_DATA PERSONAL_DATA`

With this format, it is impossible to know if _name_ and _address_ are one or two different entities.
Did you consider this issue?

Thanks!

**Comment by edobobo** [comment]
Hi,
actually, you should consider using the BILOU tags in this case.
This a stack answer that explains the format: https://stackoverflow.com/questions/17116446/what-do-the-bilou-tags-mean-in-named-entity-recognition

**Comment by JuanFF** [comment]
Thank you very much @edobobo 
You 're right!
